atom_style      atomic
units           metal
boundary        p p p
read_data       ../step_0/neb_5.data

mass     1 58.6934
mass     2 58.933195
mass     3 47.867
mass     4 91.224
mass     5 178.49

pair_style      snap
pair_coeff      * * ../../../../../potentials/HEA_v3_trial3.snapcoeff ../../../../../potentials/HEA_v3_trial3.snapparam Ni Co Ti Zr Hf
neighbor        1.0 bin
neigh_modify    every 5 delay 0 check yes

compute		sta all stress/atom NULL
compute		vol_atom all voronoi/atom
compute   pea all pe/atom
variable	va atom c_vol_atom[1]
variable	sa_xx atom 1E-4*c_sta[1]/v_va
variable	sa_yy atom 1E-4*c_sta[2]/v_va
variable	sa_zz atom 1E-4*c_sta[3]/v_va
variable	sa_xy atom 1E-4*c_sta[4]/v_va
variable	sa_xz atom 1E-4*c_sta[5]/v_va
variable	sa_yz atom 1E-4*c_sta[6]/v_va
variable	sa_hydro atom (v_sa_xx+v_sa_yy+v_sa_zz)/3.0
variable	sa_von atom sqrt(0.5*((v_sa_xx-v_sa_yy)^2+(v_sa_yy-v_sa_zz)^2+(v_sa_zz-v_sa_xx)^2)+3.0*((v_sa_xy)^2+(v_sa_xz)^2+(v_sa_yz)^2))
variable  pea atom c_pea

dump		1 all custom 1000 md_npt_dump5.cfg id type x y z v_pea v_sa_hydro v_sa_von
dump_modify 1 sort id




run 0
clear
