# Initialize simulation
atom_style	atomic
units		metal
read_data	Fe.lmp

mass		1 55.845

# snap
pair_style	eam/alloy
pair_coeff	* * ../../../potentials/Fe_Mishin2006.eam.alloy Fe

# Setup standard output
thermo_style	custom step temp pe pxx pyy pzz density
thermo		100


# Define some properties you are instrested
variable	lenx equal lx
variable	leny equal ly
variable	lenz equal lz

compute		sta all stress/atom NULL
compute		vol_atom all voronoi/atom
variable	va atom c_vol_atom[1]
variable	sa_xx atom 1E-4*c_sta[1]/v_va
variable	sa_yy atom 1E-4*c_sta[2]/v_va
variable	sa_zz atom 1E-4*c_sta[3]/v_va
variable	sa_xy atom 1E-4*c_sta[4]/v_va
variable	sa_xz atom 1E-4*c_sta[5]/v_va
variable	sa_yz atom 1E-4*c_sta[6]/v_va
variable	sa_hydro atom (v_sa_xx+v_sa_yy+v_sa_zz)/3.0
variable	sa_von atom sqrt(0.5*((v_sa_xx-v_sa_yy)^2+(v_sa_yy-v_sa_zz)^2+(v_sa_zz-v_sa_xx)^2)+3.0*((v_sa_xy)^2+(v_sa_xz)^2+(v_sa_yz)^2))
# Set up and run MD in NPT ensemble
neighbor	1.0 bin
neigh_modify	every 5 delay 0 check yes 
reset_timestep	0

dump		1 all custom 100 min_dump.cfg id type x y z v_sa_hydro v_sa_von
minimize	0.0 0.02 5000 10000
undump		1

###########################
